Fix to array shorthand not defined
DataDome/sliceline pull request #61
Opened 2024-09-26 09:45 UTC by ythevalil-dd

The shorhand `A` for the `toarray` method is not always available on recent versions of scipy. This PR changes the shorthand uses to the full method name to ensure we don't run into issues on python 3.11.

2024-09-26 13:32 UTC, adedaran requested changes

2024-09-26 13:32 UTC, adedaran commented on sliceline/slicefinder.py
Why did you keep `.A` at lines 245, 379, 398, 481 and 508?

2024-09-26 15:33 UTC, ythevalil commented on sliceline/slicefinder.py
The `.A` shorthand is no longer available for the `coo_matrix` object in `scipy`, and the other objects still using the shorthand are other types. These other types only have the shorthand implemented and don't have the standard fullname `toarray` method, so we need to keep the other lines as they are.

2024-09-26 15:37 UTC, adedaran commented on sliceline/slicefinder.py
Can you document it somewhere please (at the first occurrence of a `coo_matrix` calling `.A`)?

2024-09-27 07:40 UTC, adedaran approved these changes

2024-09-27 07:41 UTC, adedaran approved these changes

2024-10-02 09:39 UTC, kkontoudi-dd approved these changes

2024-10-07 07:43 UTC, florent-pajot approved these changes

2024-10-07 08:20 UTC, merged